[dev]
port = 3000
ws_port = 3001

[site]
script_urls = []
style_urls = [
  'https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css',
  'https://cdn.jsdelivr.net/npm/prismjs@1.29.0/themes/prism-tomorrow.min.css'
]

[meta]
title = "About this Site"
description = "This site written in Rust, use rustyink as static site generator, and hosting in netlify. All konten create by writer with Neovim text editor via the Arch Linux operating system"
og_image_url = "https://callmedar.github.io/blog/images/og.png"
base_url = "https://callmedar.github.io"

[navigation]
links = [
    { label = "Home", url = "/" },
    { label = "About", url = "/about/" },
    { label = "Blog", url = "/blog/" },
    { label = "GitHub", url = "https://github.com/syuhendar729" },
    { label = "Instagram", url = "https://instagram.com/syuhendar729" },
]
